---
all:
  hosts:
    cp-1:
      ansible_host: 62.84.118.181
      ansible_user: ubuntu
    node-1:
      ansible_host: 62.84.114.174
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        cp-1:
    kube_node:
      hosts:
        node-1:
    etcd:
      hosts:
        cp-1
    k8s_cluster:
      vars:
        supplementary_addresses_in_ssl_keys: 62.84.118.181
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
