---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-back-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: {{ .Values.service.port.backend }}
      targetPort: {{ .Values.service.targetPort.backend }}
  type: {{ .Values.service.type }}