---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.service.port.db }}
      targetPort: {{ .Values.service.targetPort.db }}
  type: {{ .Values.service.type }}