---
all:
  hosts:
    cp-1:
      ansible_host: 51.250.68.97
      ansible_user: ubuntu
    node-1:
      ansible_host: 51.250.81.158
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        cp-1:
    kube_node:
      hosts:
        node-1:
    etcd:
      hosts:
        cp-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}