---
- name: Hello world
  hosts: all

  tasks:
    - name: "Deploy app"
      command: /usr/local/bin/kubectl create deployment hello-node --image=k8s.gcr.io/echoserver:1.4

    - name: "Expose port"
      command: /usr/local/bin/kubectl expose deployment hello-node --type=LoadBalancer --port=8080