all:
  hosts:
    cp-1:
      ansible_host: 51.250.78.54
      ansible_user: ubuntu
    node-1:
      ansible_host: 51.250.72.210
      ansible_user: ubuntu
    node-2:
      ansible_host: 51.250.78.103
      ansible_user: ubuntu
    node-3:
      ansible_host: 51.250.77.45
      ansible_user: ubuntu
    node-4:
      ansible_host: 51.250.77.18
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        cp-1:
    kube_node:
      hosts:
        node-1:
        node-2:
        node-3:
        node-4:
    etcd:
      hosts: 
        cp-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}

