---
replicaCount:
  db: 1
  frontend: 2
  backend: 2

namespace: default

image:
  repository:
    postgres: postgres
    frontend: moshipitsyn/k8s-frontend
    backend: moshipitsyn/k8s-backend
  pullPolicy: IfNotPresent
  tag:
    postgres: 13-alpine
    frontend: v1
    backend: v1

service:
  type: ClusterIP
  port:
    frontend: 8000
    backend: 9000
    db: 5432
  targetPort:
    frontend: 80
    backend: 9000
    db: 5432