---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multitool-1
  name: pod-secret-mount
  namespace: default
spec:
  containers:
    - image: praqma/network-multitool:alpine-extra
      imagePullPolicy: IfNotPresent
      name: network-multitool
      volumeMounts:
        - name: certs-dir
          mountPath: /test-secret
  volumes:
    - name: certs-dir
      secret:
        secretName: domain-cert
  terminationGracePeriodSeconds: 30