---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multitool-2
  name: pod-secret-env
  namespace: default
spec:
  containers:
    - image: praqma/network-multitool:alpine-extra
      imagePullPolicy: IfNotPresent
      name: network-multitool
      env:
        - name: SECRET_USER
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: user
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: password
  terminationGracePeriodSeconds: 30
