---
all:
  hosts:
    cp-1:
      ansible_host: 51.250.5.244
      ansible_user: ubuntu
    node-1:
      ansible_host: 51.250.76.212
      ansible_user: ubuntu
    node-2:
      ansible_host: 51.250.75.12
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        cp-1:
    kube_node:
      hosts:
        node-1:
        node-2:
    etcd:
      hosts:
        cp-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}