apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-back-dpl
  labels:
    app: frontend-backend
spec:
  selector:
    matchLabels:
      app: frontend-backend
  template:
    metadata:
      labels:
        app: frontend-backend
    spec:
      containers:
      - image: moshipitsyn/k8s-frontend:v1
        imagePullPolicy: IfNotPresent
        name: frontend
        ports:
        - containerPort: 80
          name: front
        env:
          - name: BASE_URL
            value: http://localhost:9000
      - image: moshipitsyn/k8s-backend:v1
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 9000
          name: back
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@postgres:5432/news