---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    server {
        server_name   localhost;
        listen        127.0.0.1:8888;

        error_page    500 502 503 504  /50x.html;

        location      / {
            root   /usr/share/nginx/html;
        }
    }
  nginx.html: |
    <html><head><h1>NGINX</h1></head>
    <body><h2>This is test static page</h2>
    </body></html>
  ConfigMapEnv: "NGINX_CONFIG"