---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-config-test
spec:
  containers:
  - name: nginx
    image: nginx:1.21.6
    imagePullPolicy: IfNotPresent
    env:
      - name: ConfigMapEnv
        valueFrom:
          configMapKeyRef:
            name: nginx-configmap
            key: ConfigMapEnv
    volumeMounts:
      - name: nginx-static-page
        mountPath: /usr/share/nginx/html/
        readOnly: true
      - name: nginx-config
        mountPath: /etc/nginx/conf.d/
  volumes:
  - name: nginx-static-page
    configMap:
      name: nginx-configmap
      items:
        - key: nginx.html
          path: index.html
  - name: nginx-config
    configMap:
      name: nginx-configmap
      items:
        - key: nginx.conf
          path: default.conf